spring.application.name=backend
spring.datasource.url=jdbc:mysql://mysql-91287f6-anurag-737c.l.aivencloud.com:25327/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${password}